### ISSUE TITLE
push should have method that takes in Installation

### ISSUE THREAD

**Issue by ysxu** [Azure/azure-mobile-apps-ios-client#104]
Current push methods take in two forms:

register(token)
register(token, templates)
We need an additional:

register(Installation)
that reflects https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.notificationhubs.notificationhubclient.createorupdateinstallation.aspx.

There's no way for customers to pass tags in from the client side currently, hence they won't be able to take advantage of the app service push endpoint tags feature.

**Comment by antitheos** [comment]
I saw in release 3.4.0 the method register with installation was added to MSPush. 
Is there an update on the expected completion on this issue?

Thanx

**Comment by elamalani** [comment]
@antitheos Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the f[uture of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
