### ISSUE TITLE
Custom filters (MSFilter) doesn't work with Swift 3.0

### ISSUE THREAD

**Issue by dhei** [Azure/azure-mobile-apps-ios-client#105]

**Comment by dmgerdes** [comment]
I'm having the same issue.  Log the issue with Microsoft a week ago.  No updates so far.

**Comment by dhei** [comment]
@dmgerdes Thanks for reporting this to us. We are working on it.

**Comment by dhei** [comment]
The issue with MSFilter should be resolved by upgrading to XCode 8.1. As long as you're using XCode 8.1 or above, you should be fine.

Btw, we released v3.3.0 today and it now officially support Swift 3.0.
