### ISSUE TITLE
Add bitcode support for iOS

### ISSUE THREAD

**Issue by lehn0058** [Azure/azure-mobile-apps-ios-client#111]
Bitcode is enabled in the project settings, but trying to archive my project that includes the MicrosoftAzureMobile.framework complains that MicrosoftAzureMobile does not have full bitcode enabled.

`MicrosoftAzureMobile(MSOperationQueue.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

**Comment by elamalani** [comment]
@lehn0058 Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us prioritize in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
