### ISSUE TITLE
Support Auth token refresh logic ADAL 2.2 

### ISSUE THREAD

**Issue by saibabu** [Azure/azure-mobile-apps-ios-client#118]
I saw one function named acquireTokenByRefreshToken in ADAcquireTokenSilentHandler Class.
How will use this function? which class we need to import for using this Function?I already checked by importing ADAcquireTokenSilentHandler class.But it says file not found..By importing **#import <ADAL/ADAL.h>**  can able to use most of the classes.But unable use acquireTokenByRefreshToken function.please help me...

**Comment by adrianhall** [comment]
This is an ADAL problem - not an Azure Mobile Apps problem.  Sorry - you are going to have to reach out to the ADAL folks.
