### ISSUE TITLE
CocoaPod Support

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-ios-client#12]
Finish test automation and publish the CocoaPod (https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/MicrosoftAzureMobile.podspec)

Original issue for services: https://github.com/Azure/azure-mobile-services/issues/786

**Comment by TotemTraining** [comment]
+1

**Comment by adrianhall** [comment]
@dhei If we are published automatically to cocoapods, please close this one.

**Comment by dhei** [comment]
Yes, it's published here: https://cocoapods.org/pods/MicrosoftAzureMobile
