### ISSUE TITLE
Login code that uses SafariViewController doesn't redirect back into the app

### ISSUE THREAD

**Issue by lehn0058** [Azure/azure-mobile-apps-ios-client#123]
The following method that uses UIWebView when logging in a user has been deprecated:
```
-(void)loginWithProvider:(nonnull NSString *)provider
              parameters:(nullable NSDictionary *)parameters
              controller:(nonnull UIViewController *)controller
                animated:(BOOL)animated
              completion:(nullable MSClientLoginBlock)completion
```

However, the new method that is replacing it does not appear to work:
```
-(void)loginWithProvider:(nonnull NSString *)provider
               urlScheme:(nonnull NSString *)urlScheme
              parameters:(nullable NSDictionary *)parameters
              controller:(nonnull UIViewController *)controller
                animated:(BOOL)animated
              completion:(nullable MSClientLoginBlock)completion;
```

When calling the new method, I pass along a urlScheme defined in my project's URL Types. I gathered this from how the ZumoE2ETest set project was setup. I verified that the scheme is setup correctly for my app by trying to open the URL in Safari and it prompted to open my app.

After calling the new method, I get the expected login screens from both Google and Microsoft, but after entering my credentials the Safari View Controller lands me on a page that says:
"You have successfully signed in.
Return to the website."

The SafariViewController never returns control to my app. If I press the done button, I get an error saying login was canceled. The app delegate method `application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:])` is never called.

**Comment by dhei** [comment]
Hi @lehn0058, a couple of question for you. 

1. Are you using latest SDK 3.2.0 or the latest version of master branch of this repo? Note that SafariViewController change has not been officially shipped yet, so SafariViewController login is not yet available from the SDK. But you can get this feature by pulling the master branch of this repo if you'd like to. I assume you are might be already doing this.

2. Have you setup the allowed external redirect URL in your app? Based on your description that you was able to sign in with the default landing page with no redirection, my guess is the allowed external redirect URL (redirect URL of your app) may has not been properly setup in your app. That is, in order for redirect to work for your app, you need to add your redirect URL to "ALLOWED EXTERNAL REDIRECT URLS" setting in "Authentication / Authorization" setting of your Mobile App in the Azure Portal. For instance, to configure our zumo e2e test app with URL scheme "ZumoE2ETestApp", we simply add "ZumoE2ETestApp://easyauth.callback" in the "ALLOWED EXTERNAL REDIRECT URLS" setting. We will provide detailed documentation & tutorials on our documentation website by the time we ship this feature. 

Thanks.

**Comment by lehn0058** [comment]
Hi @dhei,

Thanks for your quick response. Yes, I am working off of Master. I was looking into adding support for the SafariViewController in my own project since Google is deprecating use of UIWebView logins when I noticed that you had already made good progress on it in just the last few weeks.

I had thought the problem was on the server side, since it appeared to think the login was successful and it needed to poke the client into taking over again. You are also correct that I do not have "ALLOWED EXTERNAL REDIRECT URLS" setup, but I don't see where to add it. Under the Authentication/Authorization section I see the Authentication Providers section with all of the providers I have setup, and the Advanced Settings "Token store", but no place to add external redirect URL's. I remember having to add redirect URL's in the Microsoft and Google app accounts outside of Azure, but those require me to have an https:// scheme.

Could you point me to where to add this in the Azure portal? Any help is appreciated!

**Comment by dhei** [comment]
Hi @lehn0058,

Thanks for confirming this. 

Yes, it is a little confusing - "ALLOW EXTERNAL REDIRECT URLS" setting is under AAD settings in the UI (as following) when "Advanced" AAD management mode is turned on. 

![screen shot 2017-01-16 at 12 20 21](https://cloud.githubusercontent.com/assets/4079255/21997892/95cfd380-dbe6-11e6-9b79-d1f45ee6572e.png)

There are at least two ways to configure this setting right now. 
1. As long as you've configured "ALLOW EXTERNAL REDIRECT URLS" settings in AAD advanced mode, your Mobile App redirect should work for all authentication providers (including Google, MSA, Facebook & Twitter). You can configure this setting even you don't use AAD at all - as long as you put the URL there for other authentication providers.
2. The more *universal* approach is to configure auth setting "allowedExternalRedirectUrls" on Azure Resource Explorer. You can navigate from your Mobile App -> Development Tools -> Resource Explorer , navigate to "authsettings" of your app, add your redirect URL to "allowedExternalRedirectUrls".

![screen shot 2017-01-16 at 12 38 46](https://cloud.githubusercontent.com/assets/4079255/21998443/b4c053d4-dbe9-11e6-9ff7-e5ca8399fc1a.png)

**Comment by lehn0058** [comment]
That worked perfectly - thank you for taking the time to explain it!
