### ISSUE TITLE
Use Module Map

### ISSUE THREAD

**Issue by dhei** [Azure/azure-mobile-apps-ios-client#129]
A modular framework is a framework that contains a module map. In order for Xcode to generate the module map file, a framework has to have an umbrella header with the same name of the framework and to have the Define Module (DEFINES_MODULE) build settings set to yes. This will bring the benefits of using "@import" instead of "#import" of the framework.

Please refer CLang documentation at http://clang.llvm.org/docs/Modules.html for more details.

**Comment by elamalani** [comment]
@dhei Closing this issue. Thanks!
Please refer to this section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps).
