### ISSUE TITLE
Add AlternatePushUrl setting for local development

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-ios-client#130]
Handle the case when development of the server is happening locally, but App Service Push is being used.

Set client.AlternatePushUrl
If not set, use client.AlternateLoginUrl (if set)
If still not set, don't worry about it

If set to the URL of the remote backend, send the push requests there instead of localhost.

**Comment by elamalani** [comment]
Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the future of Azure Mobile Apps. At this time, we are not adding any new features in the SDK.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
