### ISSUE TITLE
Incorrect error reporting. I wish there was no error to begin with.

### ISSUE THREAD

**Issue by Shmaff** [Azure/azure-mobile-apps-ios-client#131]
Hi,

I'm testing my application and in the morning when I begin work, I notice an error that goes away after the first attempt to connect.

`Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1400 "The predicate is not supported." UserInfo={NSLocalizedDescription=The predicate is not supported.}`

The system is not providing the correct error here as my next attempt to connect succeeds.

    let query = table!.query()
    query.predicate = NSPredicate(format: "id BEGINSWITH[c] %@", recordString) // LIKE is not supported. Use BEGINSWITH or CONTAINS
    query.selectFields = [fieldString]
    query.read { (result, error) in
        if let error = error {
            print(error)
        } else {
            // Continue with good stuff
        }
    }

Why is there an error when performing a query like this if there has been some inactivity between the client and server?

If this isn't the correct place to post this kind of problem, please point me to where is better!

I'll complain that LIKE isn't supported by predicates another time. 😉

**Comment by elamalani** [comment]
@Shmaff Were you able to resolve this issue? I'm closing it as it's been older than a year but feel free to contact us if you have any questions. Thanks!
