### ISSUE TITLE
App crashing in MSSyncContext when ManagedObjectContext save is called

### ISSUE THREAD

**Issue by DanTheDalesMan** [Azure/azure-mobile-apps-ios-client#133]
I'm currently using the latest build of the sdk and I'm running into an issue where by when I call save on the ManagedObjectContext the app is crashing at various points with in MSSyncContext. The last crash I managed to trap was at line 204 [self.operationQueue addOperation:operation orError:&error];

I'm receiving an EXC_BAD_ACCESS. 

Has anyone else experienced any issues?

**Comment by MatkovIvan** [comment]
Hi @DanTheDalesMan 
Sorry for the long delay.

Looks like it fixed in [my commit](https://github.com/Azure/azure-mobile-apps-ios-client/commit/de05705cf0a3433438b9b930c0034aefde2a78f0).
Fix will be available in next version.

**Comment by DanTheDalesMan** [comment]
That's brilliant thank you!
