### ISSUE TITLE
Authentication stopped working

### ISSUE THREAD

**Issue by nor0x** [Azure/azure-mobile-apps-ios-client#134]
I'm using Azure Mobile Apps with the .NET SDK as a backend for my iOS app. The authentication done via Facebook. Yesterday out of nowhere (no code changes either on backend or app) the authentication with Facebook failed. The login inside the iOS client app is done via

`self.client?.login(withProvider:"facebook", token: ["access_token" : FBSDKAccessToken.current().tokenString] ){ (user, error) in }`
By calling this function I'm getting the following result, on the client.

`Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "You do not have permission to view this directory or page."`
By inspecting the streaming logs of Azure Mobile Apps, I found out that the backend gets an `Unauthorized 401.71` return back from calling the Facebook Graph API.

Streaming Log:

```
Microsoft.Azure.AppService.Authentication Verbose: 0 : Received request: POST https://XXXXXXXXXX.azurewebsites.net/.auth/login/facebook
'w3wp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols.
'w3wp.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. 
Microsoft.Azure.AppService.Authentication Verbose: 0 : Calling into external HTTP endpoint GET https://graph.facebook.com/oauth/access_token.
Microsoft.Azure.AppService.Authentication Information: 0 : Sending response: 401.71 Unauthorized
```
I already tried cloning the Mobile App in Azure and creating a new Facebook App, without success.

I have opened a new Thread on StackOverflow in order to get some kind of information on how to fix this. It seems that something in Azure Mobile Apps got changed which causes the broken authentication. I can just report from an [iOS - Facebook] perspective, but other users are reporting the same behavior (see links at the end of this post). I hope to get some kind of info on this ASAP - users on production are unable to login at the moment.

[StackOverflow Thread](http://stackoverflow.com/questions/43064206/azure-mobile-apps-facebook-authentication-stopped-working/43067509#43067509)
[Post in MSDN Forums](https://social.msdn.microsoft.com/Forums/en-US/d39bd088-94c2-4a9c-9a79-389ad53192bb/facebook-authentication-not-working?forum=azuremobile)

**Comment by dhei** [comment]
This issue should already been fixed by App Service a few days ago. For more information, please refer to [this ](https://social.msdn.microsoft.com/Forums/azure/en-US/397f6952-57bf-4c28-b383-6bba08d28f9a/facebook-login-failures-with-app-service-authentication-authorization?forum=windowsazurewebsitespreview)MSDN forum thread. Close it.
