### ISSUE TITLE
Single Sign on with ADALiOS, loginWithProvider:token: not working

### ISSUE THREAD

**Issue by antitheos** [Azure/azure-mobile-apps-ios-client#14]
In the Azure Mobile Apps client for iOS (https://github.com/Azure/azure-mobile-apps-ios-client), the MSClient class provides a method

-(void)loginWithProvider:(nonnull NSString *)provider
               token:(nonnull NSDictionary *)token
          completion:(nullable MSClientLoginBlock)completion; 
I am trying to use this method with a token retrieved from the ADALiOS. I am following this tutorial (https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-ios-aad-sso/). This tutorial is before the November update to Mobile Apps

Is it possible to use AD single sign on with Azure Mobile Apps?

**Comment by phvannor** [comment]
Yes it should be possible.  I'd start by reviewing this updated AAD setup post here: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-how-to-configure-active-directory-authentication/

What error are you getting back from that call?  

I know there is a potential issue with the audience not matching.  I think the workaround that is to make sure the ResourceURI referenced from ADAL is the same as the App ID URI for the web application registration in AAD. Which should just be the URL of your site root (HTTPS scheme).

@mattchenderson can you comment?

**Comment by antitheos** [comment]
this the error message I get

com.Microsoft.WindowsAzureMobileServices.ErrorDomain Code=-1302 "You do not have permission to view this directory or page." UserInfo={NSLocalizedDescription=You do not have permission to view this directory or page.}

**Comment by antitheos** [comment]
@phvannor  Thanx for providing the information above.
Following the instructions in the link i am running into another issue.  If I have a mobile app configured with express authentication I am not able to see it as one of the options for under "Permissions to other Apps"

**Comment by antitheos** [comment]
@phvannor I have followed the instructions at https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-how-to-configure-active-directory-authentication/ and still get the same error message

**Comment by phvannor** [comment]
you checked the audience is correct as well?

You should have more details in your server logs, can you go to settings -> diagnostic logs, and turn on app logs at verbose.  Then open the streaming logs blade (you may need to add it via add tiles).  Once that says connected, try logging in again and see what gets output.

**Comment by antitheos** [comment]
I had not checked the audience.
The streaming log do refer to the audience

JWT validation failed: IDX10214: Audience validation failed.

How do you set/configure the audience

**Comment by phvannor** [comment]
I put some notes above, I copied from a different conversation: "make sure the ResourceURI referenced from ADAL is the same as the App ID URI for the web application registration in AAD. Which should just be the URL of your site root (HTTPS scheme)."

Unfortunately, I haven't personally tried this scenario so I can't clarify, if I get a chance I do mean to walk through it manually myself.  If it doesn't make sense hopefully @mattchenderson can fill us in, or you may try asking on StackOverflow/etc.

This is a temporary bug with EasyAuth on Web Apps, but this way will continue to work as well once the fix roles out as wel.

**Comment by antitheos** [comment]
So here are the logs
2015-12-02T00:14:10  PID[9624] Verbose     Received request: POST https://schedule-professionalradiaology.azurewebsites.net/.auth/login/aad
2015-12-02T00:14:10  PID[9624] Warning     JWT validation failed: IDX10214: Audience validation failed. Audiences: *'https://<app url>'*. Did not match:  validationParameters.ValidAudience: *'<aad web app client id>'* or validationParameters.ValidAudiences: *'http://<app url>'*.
2015-12-02T00:14:10  PID[9624] Information Sending response: 401.71 Unauthorized

So from above looks like it is failing because the validation parameter is expecting *http* but it is receiving *https*

**Comment by antitheos** [comment]
This what I had to make following changes do... 
In the portal I changed the **APP ID URI**  =  **http://[app url]**
In the mobile app I changed the **resourceURI**  =  **http://[app url]**

This did the trick.

**Comment by phvannor** [comment]
Looks like there is another bug in the portal that caused you to get http:// as well.  I've raised that issue internally for review as well.

**Comment by phvannor** [comment]
Closing here, since the fix needs done on the EasyAuth pipeline/etc.  I don't have a link to that work since  its not on GitHub.  @mattchenderson can we do a blog post once the fix goes live?

**Comment by yvdh** [comment]
Same error https versus http in audiences. Workaround does not work because I get an application not found, even after several restarts ...
