### ISSUE TITLE
invoke api cancel the request

### ISSUE THREAD

**Issue by Nazgaul** [Azure/azure-mobile-apps-ios-client#152]
Is there a way to cancel invoke api request?

for instance the user is on a page and invoke the api occur and in the middle of the request he hit back. i want to cancel the existing request.

**Comment by elamalani** [comment]
@Nazgaul Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the f[uture of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
