### ISSUE TITLE
invoke api handle error

### ISSUE THREAD

**Issue by Nazgaul** [Azure/azure-mobile-apps-ios-client#153]
Is there a way parse the nserror receieved when using invoke api?

on my server side i pass different status code for different error. i get the error object and when i debug i see the full description but in the code i got no way to extract it and use it to do different jobs on the client side.

**Comment by elamalani** [comment]
@Nazgaul Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
