### ISSUE TITLE
application crash on NSUserDefaults setObject

### ISSUE THREAD

**Issue by Nazgaul** [Azure/azure-mobile-apps-ios-client#156]
Hi.
Sometime on the crash logs and on uninstall and reinstall via emulator my app crashes.

this is the location

`@synthesize installId = _installId;
-(NSString *) installId
{
    if(!_installId) {
        NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
        _installId = [defaults stringForKey:@"WindowsAzureMobileServicesInstallationId"];
        if(!_installId) {
            CFUUIDRef newUUID = CFUUIDCreate(kCFAllocatorDefault);
            _installId = (__bridge_transfer NSString *)CFUUIDCreateString(kCFAllocatorDefault, newUUID);
            CFRelease(newUUID);
        
            //store the install ID so we don't generate a new one next time
            [defaults setObject:_installId forKey:@"WindowsAzureMobileServicesInstallationId"];
            [defaults synchronize];
        }
    }
    
    return _installId;
}`

the crash is happening on this line 
  [defaults setObject:_installId forKey:@"WindowsAzureMobileServicesInstallationId"];

I dont have more details since xcode doesn't give me more. 
When i first start up my app i do 2 get request at the same time. maybe there is a race condition?

**Comment by michael-snapptec** [comment]
@Nazgaul 
What are you trying to accomplish here? If you're just looking for a new UUID/GUID as an app identifier, this code might be a little bit simpler:

    NSUUID *uuid            = [NSUUID UUID];
    NSString *uuidString    = [uuid UUIDString];

Anyway, are you sure that your `_installId` is always created and correctly populated with a valid `NSString` object before you try to save it to `NSUserDefaults`? Because none of this code looks like it has anything to do with Azure or the Azure SDK; just plain ol' Objective-C/Cocoa.

**Comment by MatkovIvan** [comment]
Hi @Nazgaul 

Despite the fact that I couldn't personally reproduce the problem, I did PR (#163) to make that part of code thread-safe.
Let me know if the issue still will be in the next version (coming soon).

**Comment by elamalani** [comment]
@Nazgaul Were you able to fix this issue? Please let us know if you need help from our team. Thanks!

**Comment by Nazgaul** [comment]
@elamalani . I don't get this crash anymore. thanks for the fix.
