### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by toftof** [Azure/azure-mobile-apps-ios-client#157]
Support carthage pls. Thank you

**Comment by elamalani** [comment]
@toftof Thanks for your suggestion but supporting Carthage in Mobile Apps SDK is not on our roadmap.

**Comment by elamalani** [comment]
@toftof Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
