### ISSUE TITLE
unable to open url hosted in azure in iOS web view

### ISSUE THREAD

**Issue by ramkrishna880** [Azure/azure-mobile-apps-ios-client#169]
We are using ADAL Ios library for login.After that when we are trying to open an URL (like terms and conditions page hosted in Azure to use across all the platforms ) in web view we are getting forbidden. but we are able to open in tune browser.
Is there any way to show in a web view. please tell a way to proceed.

**Comment by bmourat** [comment]
Hi @ramkrishna880 

Could you please provide more info on this issue, because I could not reproduce it. It would be very helpful if you could provide some demo project to reproduce this or describe steps of how you are trying to log in and open url in webview, with code examples.

Thanks!

**Comment by elamalani** [comment]
@ramkrishna880 Were you able to resolve the issue? If not, please provide more info so that we can investigate it at our end.

**Comment by elamalani** [comment]
@ramkrishna880 We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
