### ISSUE TITLE
MSSyncTable incremental Pull is not working.

### ISSUE THREAD

**Issue by SP74** [Azure/azure-mobile-apps-ios-client#171]
Hi All,

We are facing an issue in incremental sync feature in iOS application. In mobile app, last sync date in MS_Table_Config table is less i.e., **2018-04-13T14:27:00.377Z** than the updatedAt date in the azure database i.e., **2018-04-13 14:29:00.924Z** on one of the table. In this case in pull request we have to get the latest records till the greatest updatedAt date and that date should reflect in the MS_Table_Config table. Neither of the them are happening.

Could anyone help us to resolve this issue.

**Comment by MatkovIvan** [comment]
Hi @SP74 

Thanks for getting in touch.
The incremental sync feature just adds one more filter based on the time value.
Could you please check that you don't add other conditions which can cut off these records. Also, is there anything useful in the server side logs?

Best,
Ivan

**Comment by SP74** [comment]
Thx @MatkovIvan for help.
