### ISSUE TITLE
MSSyncTable incrimental sync not working

### ISSUE THREAD

**Issue by nareshy-menlo** [Azure/azure-mobile-apps-ios-client#173]
I am facing the same issue in iOS
```
MSQuery *query = [self.syncTable query];
[self.syncTable pullWithQuery:query queryId:nil completion:^(NSError *error) {
}];
```

This function can get all the records from the server. But when i used the queryId like
```
MSQuery *query = [self.syncTable query];
[self.syncTable pullWithQuery:query queryId:@"AllRecords" completion:^(NSError *error) {
}];
```
Its getting partial data from the server. Any help here?

**Comment by SP74** [comment]
Hi @nareshy-menlo,

If you use "queryId:@"AllRecords", This will pull all(CUD) latest records from last pull.

CUD - created, updated and deleted one's update to the local datable.

**Comment by MatkovIvan** [comment]
Hi @nareshy-menlo 

Thanks for getting in touch.
To use the incremental sync feature your data should have meaningful `updatedAt` values. So, please make sure that true for your data.

You can find more details how offline synchronization (including incremental sync) works [here](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync#how-sync-works).

Best,
Ivan

**Comment by nareshy-menlo** [comment]
Hey @MatkovIvan, Thank you for replay, I have checked Azure DB and it has valid data in `updatedAt` column, I have also compared  records having problem, to those which are syncing properly, But i didn't find any difference in any columns.

**Comment by MatkovIvan** [comment]
Do you use unique query name for each logical query in your app? Different pull operations could overwrite the same incremental sync timestamp and your queries can return incorrect results.

**Comment by nareshy-menlo** [comment]
@MatkovIvan, I have only one query for each table and using different queryId for each table.

**Comment by MatkovIvan** [comment]
@nareshy-menlo Maybe there are some errors or other useful information in the logs from SDK? Or the logs from the server side?

**Comment by hashmurali** [comment]
Did anyone manage to resolve the issue?

**Comment by nareshy-menlo** [comment]
Make sure you have default audit columns(createdAt, updatedAt, and version) in local database.

**Comment by bmourat** [comment]
Hi @hashmurali,

What is it, that is not working for you? Could you provide some specific information on your problem (info on table structure, code snippets) to perform an investigation?

Best,
Murat

**Comment by bmourat** [comment]
I'm closing this issue for now, but feel free to reopen it if you'll have any questions!
