### ISSUE TITLE
Upsert for all items in a table each pulling

### ISSUE THREAD

**Issue by lexin** [Azure/azure-mobile-apps-ios-client#177]
Hi. 
I use MSSyncTable for sync process between server and application. All works fine except one case. 
I have near 20 tables. And do pull after the first installation of application. Each next run I just call pull for getting changed data. It works correctly - just simply check for updated items and pull them. In case there are no changes - it takes a few time. **But one table each time pulls all rows, like from scratch.** That is why each time UPSERT methods calls for all rows in this table. I can't catch te reason. 
1. I checked updatedAt field - it has value 554985691.289 for all rows. And doesn't changed.
2. Version field also is the same. Objects in DB are not changed by any way. 
3. I noticed also that for some of the records from other table UPSERT calls each time too, but it's only 2-5 items for each table (and table could have 1k-3k items). And I could not find any reason for that. 

Here is one of the objects which will be upserted 
 {
        createdAt = "2018-06-05 08:43:57 +0000";
        defaultOptionValueId = "<null>";
        deleted = 0;
        id = "F5BE4008-4B75-5AF3-7297-79DC16931622";
        modelId = "1";
        optionId = "2";
        type = options;
        updatedAt = "2018-08-03 10:41:31 +0000";
        version = "AAAAAAAF6E4=";
    },
 
Does anybody know potential reasons of this behavior?

**Comment by MatkovIvan** [comment]
Hi @lexin,

Thanks for getting in touch!
This is by design.
Incremental sync feature stores latest `updatedAt` value and then adds the filter to select only entities with `updatedAt` value **greater or equal** than you already have on the device.

Related issues: https://github.com/Azure/azure-mobile-apps-net-server/issues/241, https://github.com/Azure/azure-mobile-apps-net-client/issues/395

Best,
Ivan

**Comment by MatkovIvan** [comment]
@lexin 
> NSManagedObject represents date attributes with NSDate objects, and stores times internally as an NSTimeInterval value that is based on GMT.

See
- https://stackoverflow.com/questions/6841579
- https://github.com/dongshuju/coredata-demo/wiki/NSManagedObject

Anyway SDK returns `NSDate` to you, right?

**Comment by lexin** [comment]
In our case there were two issues with that 
1. At server side there were 7 digits after point. An on mobile part in DB we had only 3 one. Potentially this difference could  caused the problem 
2. Also in our table 2k records had the same updatedAt value, that is why SDK tries to find oldest date just used value which was equal for all records.  So, we changed manually this field for one of the record for greater and now system rePull only one this record. It's OK. 

@MatkovIvan Thanks for your answer.

**Comment by MatkovIvan** [comment]
You are welcome. I'm glad that you solved your problem. I guess the workaround from (2) should solve (1) as well.
