### ISSUE TITLE
Unable to Authenticate Azure ADAL iOS Swift Library to access Azure Mobile Apps Easy Tables Data 

### ISSUE THREAD

**Issue by kkadapa** [Azure/azure-mobile-apps-ios-client#183]
Hi i opened this issue and i've been routed here to get help [issueURL](https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/1348) 

I am religiously following [this](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal) documentation for client.login method... is this outdated? All i want is the access-token to talk to my easy tables for smooth communication. When using ADAL i get access-token.. can i use that token to call easy tables data? Should i use MicrosoftAzureMobile sdk to talk to the backend Azure Easy tables which i am doing now or MSAL or is there anything inbuilt sdk using ADAL to talk to easy tables? i thought i can use [this](https://github.com/AzureADQuickStarts/NativeClient-iOS) sample but i am so confused...

**Comment by bmourat** [comment]
Hi @kkadapa 
I wonder why are you using ADAL for authentication, why not use authentication built in Azure Mobile Apps SDK for iOS? You can find how to add auth to your app [here](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-get-started-users).

**Comment by kkadapa** [comment]
@bmourat thanks for your response... i started from [this](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#adal) and it says use ADAL and the link that you are referring to is confusing coz i am not sure which SDK it is and it's indicating to go to [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication) for AAD which i did already and followd the **(Optional) Configure a native client application**..  I am getting AccessToken from ADAL and i am passing that to MicrosoftAzureMobile `self.client.login(withProvider: "aad", token: payload, completion: { (MSUser, Error) in`... i was able to get the data from Easy Tables (Azure SQLServer) but what should i do for subsequent calls is what i am unaware... should i make silent call using cache refreshed token like [this](https://stackoverflow.com/questions/44168741/ios-adal-make-silent-call-using-refresh-token/44170226#44170226)??

**Comment by bmourat** [comment]
@kkadapa I've tried using authentication built in Azure Mobile Apps SDK and it gives me the same error as yours. That's strange. Let me investigate this a little.

**Comment by MatkovIvan** [comment]
Hi @kkadapa,

I've contacted with @bmourat and unfortunately his reproduction doesn't produce the same error.
So, we still don't have reproduction 😞 

My guess is kind of setup issue and don't directly related to this *client* sdk.
I've found mention of `IDX10500` error code [here](https://stackoverflow.com/a/48155571/1703290). Maybe this is your case?

Also, you can try to cache the auth token directly. See [this doc](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-windows-store-dotnet-get-started-users#tokens) as reference. It is about .net SDK, but the approach can be used in this sdk too. Swift version of that snippet:
```swift
   client.currentUser = MSUser(userId: userId)
   client.currentUser?.mobileServiceAuthenticationToken = token
```

**Comment by kkadapa** [comment]
Hi @MatkovIvan thank you for the response. I did try the below:

 self.client.currentUser = MSUser.init(userId: self.currentAccount()?.userInformation?.userId)
 self.client.currentUser!.mobileServiceAuthenticationToken = result.tokenCacheItem.accessToken
     
but i still get the same error **Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "{"code":401,"message":"IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier\u000d\u000a    (\u000d\u000a    IsReadOnly = False,\u000d\u000a    Count = 2,\u000d\u000a    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash =** is this because i am trying to access data from a Azure Mobile App Easy Tables? and this X509 is certificate error? I don't get this when i call acquireToken i only get this when i do acquireTokenSilent.... i am puzzled as i am inventing this process and i don't see any process documentation with regards to how to use ADAL to obtain data from Azure Mobile App Easy Tables. Would you be able to kindly point me in the right direction?

**Comment by MatkovIvan** [comment]
> Also, you can try to cache the auth token directly.

I mean cache and set `mobileServiceAuthenticationToken`, not the token from ADAL.
```swift
self.client.login(withProvider: "aad", token: payload, completion: { (user, error) in
  user.mobileServiceAuthenticationToken // <<-- This one
})
```

Did you debug the second token (or print it to the logs)? Does it look right?
Also, [the use of common authority](https://stackoverflow.com/a/29768742/1703290) can cause a similar issue.

Since the SDK works fine with `acquireToken`, I believe that is not issue of this SDK. Unfortunately, there is no good tutorial that describes all the nuances about this integration scenario.

Hope links above help you to figure out what's wrong in your setup.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

**Comment by kkadapa** [comment]
@MatkovIvan Sorry for the tardy response, i am caching the token but the problem is calling **ADAL** for acquireTokenSilent and then using that refreshtoken to call **MicrosoftAzureMobile SDK** to query to Easy Tables data which is failing or may be my approach is wrong, please see below:

```
let authContext = ADAuthenticationContext(authority: authority, error: error)
guard let applicationContext = authContext else { return }
applicationContext.acquireTokenSilent(withResource: resourceId, clientId: kClientID, redirectUri: adredirectUri, userId:currentAccount()?.userInformation?.userId) { (result) in
```

`self.client.currentUser!.mobileServiceAuthenticationToken = result.tokenCacheItem.accessToken`

Since, i am using two SDK's to query data from Easy Tables it's a bit confusing... Also the token i get for the first time (not calling acquireTokenSilent) is only good for 1hour and my problem is only with subsequent requests.

**Comment by MatkovIvan** [comment]
Yes, I got your case.

Use `mobileServiceAuthenticationToken` for caching and directly set, but not token from ADAL. To get this token use the snippet that I posted above:

> ```swift
> self.client.login(withProvider: "aad", token: payload, completion: { (user, error) in
>   user.mobileServiceAuthenticationToken // <<-- This one
> })
> ```

---

> `result.tokenCacheItem.accessToken` 

Did you debug this token (or print it to the logs)? Does it look correct?

**Comment by kkadapa** [comment]
Yes, i did here is the accessToken and i presume it looks good:

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5iQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAi14VWFYd0tSU0xqTUhHUSJ9.eyJhdWQiOiJkMjMwZjZmNi1mMjA5LTRiZTUtOGE3Yy0xZWZjYjRmZjQ2ZDQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83Zjc4NmU4NS0yYjYxLTRiYmUtYTc5Ni03MWU5MWU1ZTdlMzgvIiwiaWF0IjoxNTQ1MDYzMDU0LCJuYmYiOjE1NDUwNjMwNTQsImV4cCI6MTU0NTA2Njk1NCwiYWNyIjoiMSIsImFpbyI6IjQyUmdZQ2hmN1psNTdrKzczUDNudkRubEFkVXlCbnNPVHdpNzFyRnFqZEwvNmNuNUN6VUEiLCJhbXIiOlsicHdkIl0sImFwcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw4YjQtdm9iczAiLCJ0aWQiOiI3Zjc4NmU4NS0yYjYxLTRiYmUtYTc5Ni03MWU5MWU1ZTdlMzgiLCJ1bmlxdWVfbmFtZSI6ImtrYWRhcGFAbm9ydGh3ZWxsLmVkdSIsInVwbiI6ImtrYWRhcGFAbm9ydGh3ZWxsLmVkdSIsInV0aSI6Im5iekY0cWlGS2tTNnVXNTh5Q2pxQUEiLCJ2ZXIiOiIxLjAifQ.NfJtfq5gfwGUX-YLI-IX0ITq1mC0Zl3CwMeNK0XjgNovAOiAnK8aiPLz5wHVJDkhV4VIvNmTGcCI1eTuJ3oBNaOtr-rQqMgE7IJI822yqhD4Fuq7qupldJD-DZ4cLhA6_BHyZSRFQcKxGQzrMV-b9_AgJBf5AbcYCAE7D0AqSnP5CcG6IaYrhjUYnbLLQLgvoJu9_c3mjqglw1bnYKvNcLR53V7tl5xxv68yl-8hInQc0mjv4Y3EHTZbj5ttYHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjtHJ78DaCHaW1IpblCN1UFKx5_rp7JclG5xxPx6aw

**Comment by MatkovIvan** [comment]
The JWT tokens can be decoded for debug reasons by https://jwt.ms/ (the tokens never leave your browser). Please compare the fields between the tokens. Are there any differences?
Also, please look at [this troubleshooting page](https://auth0.com/docs/quickstart/backend/webapi-owin/03-troubleshooting). The error 'IDX10500' is mentioned in the signature algorithm point.

**Comment by kkadapa** [comment]
Thanks @MatkovIvan exactly this is the method ( -(void)refreshUserWithCompletion) i already tried few times to use this, i believe i should initialize like below and then refresh 

```
self.client.currentUser = MSUser.init(userId: self.currentAccount()?.userInformation?.userId)
self.client.refreshUser(completion: { (MSUser, Error) in
            
        })

```
Since, i don't see anywhere in the documentation of both SDK's... i got puzzled. Let me try this and i will get back to you.

**Comment by MatkovIvan** [comment]
Also before refreshing set the cached token

> ```swift
> self.client.login(withProvider: "aad", token: payload, completion: { (user, error) in
>   user.mobileServiceAuthenticationToken // <<-- This one
> })
> ```

> `client.currentUser?.mobileServiceAuthenticationToken = token`

**Comment by kkadapa** [comment]
After setting the cached token which i believe will expire after 1hour I get an **Error**  Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1513 "Refresh failed with a 403 Forbidden error. The refresh token was revoked or expired." UserInfo={NSLocalizedDescription=Refresh failed with a 403 Forbidden error. The refresh token was revoked or expired., NSUnderlyingError=0x6000018b4ab0 {Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "" UserInfo={NSLocalizedDescription=}}}

but i was able to get the data from the database, which is a bit strange.

**Comment by kkadapa** [comment]
Thank you for the response @matkovlvan. I did try to set the user and called the refreshUser and encountered the following:

Error is  Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1512 "Refresh failed with a 401 Unauthorized error. Credentials are no longer valid." UserInfo={NSLocalizedDescription=Refresh failed with a 401 Unauthorized error. Credentials are no longer valid., NSUnderlyingError=0x600000c4a490 {Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "" UserInfo={NSLocalizedDescription=}}}
ERROR in rtesttable Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "" UserInfo={com.Microsoft.MicrosoftAzureMobile.ErrorResponseKey=<NSHTTPURLResponse: 0x600000245000> { URL:

so are you saying after successful first time Auth i just have to do GET /.auth/refresh with the endpoint of the app to avoid token expiration? and this has lifetime expiration.

**Comment by jwallra** [comment]
Hi @kkadapa - have you tried the method you mentioned (GET the `/.auth/refresh` endpoint after first auth)?  We have some documentation [here](https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/realworld/#refresh-tokens) which gives more detail about refresh tokens, but the code examples are explicitly for Xamarin.  The concepts should be the same, though, so hopefully it helps a bit.  The whole authentication chapter may also give you a better picture of how the SDK is used.

**Comment by MatkovIvan** [comment]
Hi there.
We haven't heard from you in a while so I'm closing this issue. Feel free to reopen/comment if this issue is still the case.
