### ISSUE TITLE
Is there a forecast for swift 4 or 5?

### ISSUE THREAD

**Issue by jonasrotilli** [Azure/azure-mobile-apps-ios-client#187]
Currently the current version of xCode is 10.2, it does not have support for swift 3. Soon this example does not work.
Is there any forecast to update this example? It would be very useful to the whole community.

**Comment by elamalani** [comment]
@jonasrotilli Thanks for using Azure Mobile Apps. Please refer to the readme page where we have shared the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). We are not making any changes in the product, so there is no plan to update the examples with Swift 4 or 5.

**Comment by veenroid** [comment]
Why? You're primary documentation for any new dev points right to this ancient materials. This is not a winning strategy. I hope you'll reconsider.

**Comment by jonasrotilli** [comment]
There is no hope, I have already left the azure, I recommend doing the same...

**Comment by veenroid** [comment]
Thanks for your reply Jonas. Where did you go instead?
________________________________

**Comment by jonasrotilli** [comment]
I continue to use the SQL Server database, Azure, but only SQL.
For mobile devices, I use Google's Firestore / Firebase to synchronize with a local database. So I have a node service to bridge this gap between SQL Server and Firestore and vice versa. It takes a lot of work, but I found the solution...
