### ISSUE TITLE
How do you do the following exactly?

### ISSUE THREAD

**Issue by oscarrod5** [Azure/azure-mobile-apps-ios-client#191]
How do you do the following exactly? I'm so lost especially on where to put "pod 'MicrosoftAzureMobile', '~> 3.4.0'" and how to select the active scheme option.
how to select the active scheme option.  Whenever I perform "pod 'MicrosoftAzureMobile', '~> 3.4.0'", it says [!] Unknown command: `MicrosoftAzureMobile,`.

**Integration Using CocoaPods**
Add the following to your podfile to include MicrosoftAzureMobile:
pod 'MicrosoftAzureMobile', '~> 3.4.0'

**Building the SDK**
Set the active scheme option to Framework\iOS Device.
Build the project using Command-B. The WindowsAzureMobileServices.framework folder should be found in the build output folder under Products\<build configuration>-iphoneos

**Comment by Jamminroot** [comment]
Hey, @oscarrod5, can you elaborate a bit, I am not sure I understood correctly.
But, in case I got you right and the question is about integrating Azure Mobile via CocoaPods, then you might want to look at those:
1) [Getting started with CocoaPods](https://cocoapods.org/#get_started) - how integration through cocoapods work (basically, creating textfile named `Podfile`, adding dependencies in format CocoaPods accepts, and running `pod install`)
2) [Podfile format](http://guides.cocoapods.org/using/the-podfile.html) - description of the `Podfile` and what CocoaPods expect to find there
3) [Integration steps](https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/README.md#integration-using-cocoapods) - how to integrate Azure Mobile in specific (which seem to have been unclear to you).
Hope that helps.

**Comment by ilyashumihin** [comment]
Hey, @oscarrod5!
We haven't heard from you in a while, so I am going to close this conversation. Should you still have any questions, please contact us again.
