### ISSUE TITLE
applicationKey is not exposed for MSClient

### ISSUE THREAD

**Issue by mohamedmansour** [Azure/azure-mobile-apps-ios-client#22]
I am trying to instantiate an MSClient with an applicationKey but it isn't exposed in the interface. Any plans adding it back in?

**Comment by phvannor** [comment]
Application key is no longer a supported concept in the Apps world.  (The server also no longer does a check for its presence)

You can roll your own via a MSFilter that adds a given Request header in to server the same purpose, and adding a ActionFilterAttribute in your server (assuming .Net based) or middleware (Node) to check for it before the request is allowed to continue.

**Comment by phvannor** [comment]
At this time we will not be adding a app key to the MSClient again
