### ISSUE TITLE
Offline: Allow NSManagedObject subclasses rather than NSDictionary

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-ios-client#28]
See: https://github.com/Azure/azure-mobile-services/issues/287 for discussion to date.

At this point I messed up the split, and missed my core merge of the MSManagedObjectObserver (see: https://github.com/Azure/azure-mobile-services/commit/37b2554ac1ccecac170d26af9d9b806156b5019c)  

I need to manually bring that over again manually (sorry for the lost history @damienpontifex)

Then review where we stand on letting users work directly with CoreData and track things behind the scenes. Next step is really to get some documentation/samples and flush it out to see what more is needed.

**Comment by damienpontifex** [comment]
No worries on the lost history @phvannor. Let me know if you need a hand working on testing/samples when copied over

**Comment by adrianhall** [comment]
We are working on refactor work, so I think this will go by the wayside at this point.
