### ISSUE TITLE
OS X : Packaging & Testing

### ISSUE THREAD

**Issue by phvannor** [Azure/azure-mobile-apps-ios-client#33]
Our SDK has support (and tests) for using it on OS X, but we offer no ship vehicle yet (nor a e2e test suite for it)  Long term we should make it easier to consume.

**Comment by damienpontifex** [comment]
I was thinking about this, and the major difference between iOS and OS X is the login UI. Following the cocoa pods distribution route, my thoughts would be to create a subspec for these. Looking at [Auth0's podspec](https://github.com/auth0/Lock.iOS-OSX/blob/master/Lock.podspec), I think a similar patter could be followed.

With a small bit of folder restructuring, the project could have a MicrosoftAzureMobile spec with a 'Core' subspec containing all the common elements (tables, sync tables, sync context etc) and then subspecs for iOS UI and OS X UI.

@phvannor If you think this may be a good way to go, I could have a look at mocking something up with this change and propose it via a PR for a look?

**Comment by adrianhall** [comment]
We are not going to be directly supporting OSX, so closing this.  The refactor #43 may assist by letting customers define their own auth/UI logic.
