### ISSUE TITLE
Configurable table endpoint

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-ios-client#37]
In [MSURLBuilder](https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/src/MSURLBuilder.m#L44) it's currently fixed that the sync table endpoints will be located at /tables/*

It would be great if this was configurable. e.g. Web API generally hosted endpoints at /api/* and it would be great if we could build on these existing APIs and utilise the mobile client without too many significant changes to the backend

**Comment by phvannor** [comment]
You want this configurable for the table's for offline sync?  Or is something not working as nicely as desired with the invokeAPI methods?

**Comment by damienpontifex** [comment]
With the offline sync.

Currently working on an existing project that we could utilise the mobile apps client but would like to utilise the existing API end points and routes

**Comment by phvannor** [comment]
is it enough to customize the routes, or do you also ultimately need to customize the Id & version/updatedat column names as well?

**Comment by damienpontifex** [comment]
There is already an existing string Guid Id, updated, version, created columns, so that's why I figured the mobile services client may work predominately well without the need for any other changes. 

If the client route/url was configurable, it may work without any significant changes to the server code.

**Comment by damienpontifex** [comment]
I was having a go at adding a configurable property to `MSClient` or `MSTable` and pass it onto `MSTableItemRequest` but it seemed to get quite 'hacky' quickly.

**Comment by phvannor** [comment]
Yeah, I've looked at this, for possible configuration via meta data like Swagger, etc in the past.  The quickest "hack" for you is going to use a MSFilter, and see if each outbound request you can change the url from tables/X to api/X and get things going.  

Push would be easy to do as well in its delegate, but since pull has no corresponding hooks yet, thats the best short term answer I know of.

**Comment by damienpontifex** [comment]
Didn't think about the MSFilter. Thanks, I'll give that a go.

**Comment by phvannor** [comment]
Let me know how it goes, esp around the columns in use.  Being more flexible is on our roadmap, so good to capture any details of examples here.
