### ISSUE TITLE
Components in swift

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-ios-client#38]
More of an enquiry: has there been a discussion about additions to the client SDK in Swift?

Obviously Apple are pushing it quite strongly, but there are other advantages such as generics, default parameters etc. New additions could be written in Swift with a migration over time.

**Comment by phvannor** [comment]
I haven't looked at this in depth, I think it may require dropping the static framework build we do and distribute solely via dynamic or CocoaPods.  Otherwise it seems that a framework can be mixed Swift/ObjC w/o much issue from Apple's docs.

**Comment by damienpontifex** [comment]
Yes, agreed it would require dropping the static framework as to my knowledge swift requires to live in a module which is only built by dynamic frameworks at the moment. I believe this would put a minimum deployment target to iOS 8.0 due to this.

**Comment by adrianhall** [comment]
Closing this as it isn't going to happen given current resourcing...
