### ISSUE TITLE
Server authentication flow should use SFSafariViewController

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-mobile-apps-ios-client#39]

**Comment by phvannor** [comment]
SFSafariViewController is only on iOS 9, need to keep MSLoginController flow(s) for iOS 8 in the meantime.

**Comment by phvannor** [comment]
Looking at this in detail, I'm not sure its possible to capture the final redirect we need to here...  The delegate only has a initialLoad complete, I'm not seeing a way to detect the final redirect to close the form and move on.

**Comment by phvannor** [comment]
Oh yes, thats right, noting this so I don't forget this detail again, the end needs to involve the AppDelegate looking for the final URI.  Similiar pattern to what we do on WindowsPhone for WAB's  AuthAndContinue.

**Comment by phvannor** [comment]
We will also want a first class UI in the portal for setting the allowedExternalRedirectUrls so that we can finish that loop w/o forcing users to use a windows cmd execute command as well.

**Comment by damienpontifex** [comment]
I believe you implement the `application:HandleOpenUrl` on the app delegate to handle the callback. Relevant presentation from WWDC for handling the callback: http://asciiwwdc.com/2015/sessions/504#t=1589.356

**Comment by edorphy** [comment]
whats missing is the OAuth provider redirects back to the azure app service not to the app itself.  If you switch out the azure callback when you setup your provider I think it would work.  I'm guessing then however, that the azure token store would not ever get your token. 

I'm going to try a redirect back to my app via universal links in the callback, from there redirect to the azure callback once the app has the data. 

I'll post back with my findings.  I added a feature request to the server git to allow user to provide url for azure to redirect to once the callback gets invoked.

**Comment by edorphy** [comment]
I didn't have any luck trying to use universal links then to call azures callback manually.

Google is dropping UIWebView login in the "next few months".

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

This will mean no one can sign into an Azure App Service using google.

**Comment by adrianhall** [comment]
Dup of #90
