### ISSUE TITLE
MSQuery pagination not working

### ISSUE THREAD

**Issue by clementappsolute** [Azure/azure-mobile-apps-ios-client#40]
Hello,

We're using `MSQuery`s to retrieve data from our Azure Mobile App, where we can easily pull a lot of data (over 1000 rows) however the `nextLink` property is always empty. Is there a specific setting that we have to enable on the Azure portal for it to be working?

Thanks,

**Comment by phvannor** [comment]
nextLink is currently only populated if you are using the .Net Server SDK, and then it will depend on the attribute you are using on your controller.  (I believe Node will get nextLink support soon, it may already have it in its newest beta)

For .Net, by default there is a PageSize of 100, which means you will get a next link when you ask for $tops > 100, i.e. $top=1000 will give you 100 records + nextLink with some kind of skip=100&top=900 logic.

($top will be the fetchLimit on the MSQuery object)

If you overrode that to use MaxTop of others, than I am not as sure as how Asp.Net/WebApi handles the nextLink logic.  

If thats what you are doing, and you see a "link : next; https://.....?$..." via PostMan/etc using the REST API and its just not populating the MSQueryResult's nextLink, let me know.

**Comment by phvannor** [comment]
[Queryable(PageSize = X)] (or MaxTop) is the attribute you should use on your table if you are overloading the default page sizes.  (Also, the default may be 50 after thinking on it, I'm not 100% sure)

**Comment by clementappsolute** [comment]
Thanks @phvannor for that detailed reply! I'll check this out with the backoffice team, thanks!

**Comment by clementappsolute** [comment]
Actually by using a REST client I inspected the headers and I'm not getting a `link : next` HTTP header field. The parameters passed are the following `?$filter=(IdMarkets%20eq%2053l)&$top=100`. I'm getting 100 fields returned.

**Comment by phvannor** [comment]
I ran quick test on a .Net based backend (http://phil-net.azurewebsites.net/tables/roundTripTable?$top=50) And I see a link header on no top or top > pageSize.  But none if top <= pageSize.  Looks like the default size is 50.

Did you try a larger size like 1000?  Or can you verify what backend (Node vs .Net) and version they have published, plus if they are using an override, like MaxTop or PageSize?

**Comment by clementappsolute** [comment]
Hello Phillip, sorry for the late reply.

I've been told we're using a .Net backend. Under the App Services tab, in Application Settings we're using a .Net framework version 4.6. I didn't find the `MaxTop` or the `PageSize` under `App settings`. However I did find these values set for the `MS_EnabledBetaFeatures`

```
AAD,appsettings,byonappcreate,byonpush,connectionstrings,dotnetruntime,externalpushentity,hybridconnections,opconcurrency,softdelete,webappmigration
```

**Comment by phvannor** [comment]
The settings I referred to don't live in the App Settings, they are actually controller attributes on the C# classes.  Like so: 
https://github.com/Azure/azure-mobile-apps-net-server/blob/master/e2etest/Controllers/Table/MoviesController.cs#L26
https://github.com/Azure/azure-mobile-apps-net-server/blob/1747c0df2f0f3b7641b93bc0155ef0ce36046178/samples/SampleApp/Controllers/GreenController.cs#L27

**Comment by clementappsolute** [comment]
@phvannor Hey Philip, thank's again for your great support.

After a chat with the team, the backend is actually in Node.JS (another part of the app is in .Net).

> (I believe Node will get nextLink support soon, it may already have it in its newest beta)

Since the nextLink isn't available for Node.JS however it may be available in its newest beta, how can we opt-in the newest beta?

From a quick [inspection](https://www.dayzure.com/post/2015/10/15/retrieve-all-objects-graph-api) on google we can get a `nextLink` if we implement custom APIs?

Thanks,

**Comment by phvannor** [comment]
The latest Node server's repo is here: https://github.com/Azure/azure-mobile-apps-node  It looks like it will send the Link header (see: https://github.com/Azure/azure-mobile-apps-node/blob/d693bf06ad3b03de31ec3f885265ab48e68eacba/src/express/middleware/nextLink.js)

Latest would be 2.0.0.beta2 (https://www.npmjs.com/package/azure-mobile-apps), probably easiest to close this issue and open a question issue on the Node repo directly for further help.

**Comment by clementappsolute** [comment]
Alright, thanks again for your help!

On Tuesday, January 5, 2016, Phillip Van Nortwick <notifications@github.com>
wrote:

> The latest Node server's repo is here:
> https://github.com/Azure/azure-mobile-apps-node It looks like it will
> send the Link header (see:
> https://github.com/Azure/azure-mobile-apps-node/blob/d693bf06ad3b03de31ec3f885265ab48e68eacba/src/express/middleware/nextLink.js
> )
>
> Latest would be 2.0.0.beta2 (
> https://www.npmjs.com/package/azure-mobile-apps), probably easiest to
> close this issue and open a question issue on the Node repo directly for
> further help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-mobile-apps-ios-client/issues/40#issuecomment-169081399>
> .
>


-- 

Merci,
Clement

—
