### ISSUE TITLE
Smaller components of library

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-ios-client#43]
Could the components of the mobile apps library be separated.

Proposed components:
- Core/Data - MSTable and other connection components
- Offline - Offline/Sync components with dependency on Core/Data
- Auth/Ui - User authentication and UI for such actions.

When distributing via cocoa pods, subspecs could be used with the default_subspecs still to include all components so no breaking change would occur. This would also allow #33 to be easier as the first two points above would only rely on Foundation code and the Auth/Ui component could have specific components for iOS and OS X separately.

This would also allow developers to just use the components of the framework they required if they had their own auth. Or just wanted to use mobile apps auth.

**Comment by elamalani** [comment]
@damienpontifex Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us prioritize in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
