### ISSUE TITLE
App-specific user management

### ISSUE THREAD

**Issue by Vortec4800** [Azure/azure-mobile-apps-ios-client#44]
I'm converting my app from using the Parse backend to a more powerful and flexible solution on Azure. My iOS app has user registration provided through Parse, where the user picks a username and password which is stored in a Users table. The user login and registration is handled through native UITextField components in the app.

At first I thought I could use Active Directory as the user management solution, but it seems that is more geared towards organizations with a set number of users/employees and not a public-facing application. I don't see how I could register a new user from the app on AD, or how I could log in using native UI.

It seems like maybe I can do all user management in code, storage/hashing of passwords, password reset, and so on, but this is sensitive information and I would prefer that the service handle this for me. Is that my only other option?

I don't know the proper channel for requesting this, but I think a service that uses a connected database for user management would be a major plus for an application like mine. I would even pay a small monthly fee for a service like this. What are the odds that the Azure team is working on something like that?

**Comment by mattchenderson** [comment]
One good channel for feedback like this is the [Azure feedback site](https://feedback.azure.com/forums/34192--general-feedback).

You are correct that AAD does not support this in the normal case - really it's not meant for registration actions at all. There is a new service in preview, [AAD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/), which provides some of the capabilities you are looking for. I don't think there is support right now for providing your own text boxes, though.

On the App Service side, we also provide mechanisms for doing sign-in with [custom accounts](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#custom-auth), but it does require you to do the password management etc. in your own code. We're looking at some better integrations with framework solutions here (e.g., ASP.NET Identity), but you should be able to start with those, which would help a bit.

We're definitely aware that this is a needed scenario, and we will be working to improve the authentication experience. For now though, your best bet is to write it yourself, try AAD B2C, or integrate another 3rd-party auth solution.

**Comment by phvannor** [comment]
Moving to -apps since it applies across all SDKs.
