### ISSUE TITLE
This vs azure-mobile-services?

### ISSUE THREAD

**Issue by weien** [Azure/azure-mobile-apps-ios-client#50]
How is this repo related to https://github.com/Azure/azure-mobile-services?

**Comment by fabiocav** [comment]
@weien Mobile Apps service is the new version of Mobile Services, and with the new version, the client SDKs that were previously maintained in the azure-mobile-services repo were broken up by client platform and moved to azure-mobile-apps-<platform>-client repos. So, in short, the source found in this repo is for the iOS client SDK for the new version of Mobile Services, Mobile Apps.
