### ISSUE TITLE
AAD App Service Authentication

### ISSUE THREAD

**Issue by egrimmius** [Azure/azure-mobile-apps-ios-client#52]
I'm trying to use azure active directory in our new mobile app (was using mobile services) with the App Service Authentication.  I set it up per Matthew Henderson's instructions at 

https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-how-to-configure-active-directory-authentication/

However, I keep on getting an error before the login window even appears - "Cannot GET /login/aad?session_mode=token"

What am I missing?

**Comment by egrimmius** [comment]
Specifically, when I try to login using loginViewControllerWithProvider, it responds with the following error:

Error Domain=com.Microsoft.MicrosoftAzureMobile.ErrorDomain Code=-1302 "Cannot GET /login/aad?session_mode=token

The MSLoginController briefly pops up before disappearing.

**Comment by phvannor** [comment]
The URL in the error looks incorrect, the 3.0 SDK should (by default) send to .auth/login/aad?session_mode=token.  

Can you verify what version you are using?  Also that you are not overriding the path via the client. loginPrefix property.

**Comment by phvannor** [comment]
@mattchenderson @cgillum any other thoughts?  Would invalid AAD setup in AAD return just the path owned by it?  

@egrimmius If the version looks ok, can you enable & open the streaming logs in the portal for your Web App and see if any logs pop up when you try to present the login controller?

**Comment by egrimmius** [comment]
@phvannor I use the SDK via cocoa pods.  Here is what I have in my pod file:

pod 'MicrosoftAzureMobile', :git => 'https://github.com/Azure/azure-mobile-apps-iOS-client.git'

The pod install or update log in terminal shows we're using 3.0.0.  Per your instructions in issue #14, I enabled verbose logging for my Web App.  Past the formatting information in the log, here's what came out on the log when I tried to present the login controller:

</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
<h3>HTTP Error 404.0 - Not Found</h3> 
<h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4> 
</div> 
<div class="content-container"> 
<fieldset><h4>Most likely causes:</h4> 
<ul> 	<li>The directory or file specified does not exist on the Web server.</li> 	<li>The URL contains a typographical error.</li> 	<li>A custom filter or module, such as URLScan, restricts access to the file.</li> </ul> 
</fieldset> 
</div> 
<div class="content-container"> 
<fieldset><h4>Things you can try:</h4> 
<ul> 	<li>Create the content on the Web server.</li> 	<li>Review the browser URL.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code and see which module is calling SetStatus. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>Detailed Error Information:</h4> 
<div id="details-left"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
<tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr> 
<tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
 
</table> 
</div> 
<div id="details-right"> 
<table border="0" cellpadding="0" cellspacing="0"> 
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://ourWebAppName:80/app.js?session_mode=token&amp;session_mode=token</td></tr> 
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\app.js</td></tr> 
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
 
</table> 
<div class="clear"></div> 
</div> 
</fieldset> 
</div> 
 
<div class="content-container"> 
<fieldset><h4>More Information:</h4> 
This error means that the file or directory does not exist on the server. Create the file or directory and try the request again. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,0,0x00000000,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p>

**Comment by phvannor** [comment]
Ok, let me see try this out locally and see if I can repro, can you note what version of the server sdk you are using for us to test with?

**Comment by phvannor** [comment]
Also, this is a new mobile app, not a migrated one, correct?

**Comment by egrimmius** [comment]
Originally, I migrated an app, tried it with the new authentication, and that failed.  I've since left that one alone, as it's currently in production, and also uses the original Mobile Services SDK.  

This issue is for a new mobile app, using this SDK.  

As for the Server SDK, I don't exactly know where to find that.  Is that the Web App application setting 'WEBSITE_NODE_DEFAULT_VERSION'?  If so, it's version 4.2.3.  The application setting 'MobileAppsManagement_EXTENSION_VERSION' is also set to 'latest'.

**Comment by phvannor** [comment]
Goto https://<yourappname>.scm.azurewebsites.net/DebugConsole, and naviagte to site/wwwroot and edit packages.json.  

You should have a line like:
  "dependencies": {
    "azure-mobile-apps": "^2.0.0-rc2",
   ...
  }

Let me know what version is specified there.

Also are you using any URL rewrite rules in web.config?

**Comment by egrimmius** [comment]
That line in packages.json reads
"azure-mobile-apps": "^2.0.0-beta3"

I am not aware of using any URL rewrite rules in web.config.  I'm managing the Mobile App completely through the Azure portal.

**Comment by egrimmius** [comment]
Since I created my Mobile App entirely using the Azure Portal, I assume it uses the Node.JS Server SDK, which is still in beta.  Do you think I would still have this problem if I used the .Net Server SDK?  Thanks for your help with this.

**Comment by egrimmius** [comment]
I found the my error that caused the problem with loginViewControllerWithProvider.  I inadvertently set the MSClient's loginPrefix to "login".  What a great rookie mistake.  Thanks again for taking a look at this.
