### ISSUE TITLE
Register for push notifications with tags

### ISSUE THREAD

**Issue by nor0x** [Azure/azure-mobile-apps-ios-client#53]
I am wondering if I can register for push notifications with specific tags (i.e. language) from an iOS app.
Before I migrated my Mobile Service to an App Service (and upgraded the SDK) there was the method:
`registerNativeWithDeviceToken:deviceToken tags:tagArray completion:`

Is there something similar or how can I handle tags with this SDK?

Thank you!

**Comment by adrianhall** [comment]
We are working on something to assist with this, but it's a little far out.  Right now the advice is to set up a Custom API in the back end to do a custom registration with Notification Hubs.

**Comment by barbayrak** [comment]
@adrianhall  I am wondering if the feature request is applied or not ? , if its not is there any documentation for tag registration to notification hub from custom api (Node js Backend)

**Comment by adrianhall** [comment]
Hi @barbayrak - it is not available as yet.  Once it is available, it will be a part of the Azure platform (and not the SDK).  We are working on it.

**Comment by adrianhall** [comment]
Replaced by #104
