### ISSUE TITLE
ApplicationKey property in MSClient readonly and never set. When used always nil.

### ISSUE THREAD

**Issue by edorphy** [Azure/azure-mobile-apps-ios-client#66]
I see that some convenience static initializers that existed within the mobile services SDK were removed in the App Service SDK. I also do not see a reference to the X-ZUMO_APPLICATION anywhere in the current App Services .Net SDK. 

Please clarify that this is staying around for a reason or remove it. I don't want to add the header manually if it will end up breaking things down the line.

Line 53 of MSClient.h
Line 14 of MSClientConnection.m
Line 246 of MSClientConnection.m

**Comment by shrishrirang** [comment]
Good point. applicationKey is no more used. Most references to it were removed, but looks like some were missed. Thanks for bringing it to our notice.
