### ISSUE TITLE
InvokeAPI doesn't seem to be sending the body of the message to the EasyAPI backend

### ISSUE THREAD

**Issue by gacilu** [Azure/azure-mobile-apps-ios-client#70]
Hi,

I have the following code in Swift calling an EasyAPI within an Azure App Service instance:

![image](https://cloud.githubusercontent.com/assets/10350521/14651261/169dbc94-0667-11e6-9efc-63b541b8c4b9.png)

And this code in the EasyAPI:

![image](https://cloud.githubusercontent.com/assets/10350521/14651282/38a2f67e-0667-11e6-8991-ad77bc214082.png)

Req.body is always undefined. If I send the json directly as parameter I receive it in the other side as req.query without problems.

Am I doing something wrong or could it be a defect?

Thanks,

GA

**Comment by shrishrirang** [comment]
Can you try specifying the content-type as application/json: `headers:@{"Content-Type: @"application/json"}` 

If this does not work, it means you are possibly using an older version of the node SDK and you need to update to 2.0.2.

**Comment by gacilu** [comment]
Hi there,
Thanks for your suggestion.
I added the header but it doesn't seem to work. I am using the 3.0.0 framework. Here you can see it in a screenshot:
![image](https://cloud.githubusercontent.com/assets/10350521/14664937/33366a94-06c7-11e6-83fb-dde78127beac.png)

Any other ideas?

**Comment by gacilu** [comment]
Hi again,
I have downloaded the app generated by Azure through the Quick Start menu with the 3.0.0 framework that comes with the app and added my code right at the beginning, and the result is exactly the same as before. req.query arrives perfectly fine but req.body stays undefined. I am using the header as you suggested. I don't know what else to try besides of making the call directly using a iOS http request. Should I try that?
Thanks,

**Comment by gacilu** [comment]
Hi again,
I pulled the framework code and checked the invokeAPI method and it looks perfectly fine to me. Making the call manually won't help I think. There must be something in the backend I guess. Any other suggestions?

**Comment by shrishrirang** [comment]
My first guess as I mentioned earlier is that you are using a version of the node SDK older than 2.0.2. You can check that by going to http://\<**your site name**\>.scm.azurewebsites.net/dev and then look at the version of azure-mobile-apps specified in package.json. If the version is older than 2.0.2 that would explain the behavior. In that case updating to the latest version of the azure-mobile-apps package (2.1.0) should help. Can you try this and let me know if it works?

**Comment by gacilu** [comment]
Sorry. I thought you were talking about the version of the iOS framework. I will check it today and I will let you know. Thank you for your help. I really appreciate it.

**Comment by gacilu** [comment]
Thank you man! I updated node and it works perfect!
