### ISSUE TITLE
InvokeAPI GET Request Always Fails

### ISSUE THREAD

**Issue by PascalJedi** [Azure/azure-mobile-apps-ios-client#72]
Hello,  

    

>   I am in the process of upgrading my mobile service to the new app service, and taking the chance to upgrade the azure sdk as well.   It seems with the 3.1 SDK that I am not able to communicate with HTTP GET custom controllers.   All post controllers work, and further all POST controllers with authentication work.   Also, the actual requests from my website work when I manually call them in a browser via the https://<site>/api/Sites?geolat=10&geolong=10 request. 

  ```
  NSMutableDictionary * parameters = [[NSMutableDictionary alloc] init];
   ...     
    [parameters setObject:geolat_val forKey:@"Geolat"];
    [parameters setObject:geolong_val forKey:@"Geolong"];
    
    [client invokeAPI:@"SitesAPI" body:nil HTTPMethod:@"GET" parameters:parameters headers:nil completion:^(id result, NSHTTPURLResponse *response, NSError *error) {
        if (error) {
            NSLog(@"Error: %@", [error localizedDescription]);
        }

```

  

>    At this point I alway receive an error message:
> error	NSError *	domain: @"com.Microsoft.MicrosoftAzureMobile.ErrorDomain" - code: 18446744073709550315	0x00007fac3b1bfb00
> 

> and
> [1]	(null)	@"NSLocalizedDescription" : @"The server returned an error."	     
> 
> Thoughts on what the issue might be?

**Comment by shrishrirang** [comment]
Did you have to specify any custom header (ZUMO-API-VERSION) when you connected to the GET APIs from browser? I just want to be sure that your site has been upgraded to the new Azure Mobile App Service.

Can you try using some HTTP traffic monitoring tool to see if there is any difference in the URL the iOS client is trying to access vs the URL you are able to connect to from browser?

Lastly, is this something you are running into after you upgraded from 3.0 to 3.1 version of the SDK?

**Comment by PascalJedi** [comment]
Hi,   I did not have to specify any custom header when I got the request using the web browser.

I haven't tried to backport back to 3.0 yet.   I will try that soon.    I think this has to do with SSL, and the fact that the website changed to an HTTPS.   I got a verbose log from the website and it said it was targeting the request to :80/api/sites?....   When I typed that into the browser it didn't work as well.

**Comment by PascalJedi** [comment]
o.k., so I think I have it... When one switches over to the new ApiService and configures social media login authentication it in the portal you have to switch off the selection "Action to take when request is not authenticated".  Basically at that point all non authenticated requests were being sent to the AAD which I had not setup.
