### ISSUE TITLE
Import Webkit missing in the framework?

### ISSUE THREAD

**Issue by gacilu** [Azure/azure-mobile-apps-ios-client#73]
Hi there,

My code was compiling fine when I had the framework version 3.0.0. I updated the framework to version 3.1.0 and I am getting the following error when compiling the same code:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in MicrosoftAzureMobile(MSLoginView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I added import WebKit in the AppDelegate of my Swift code and it started compiling fine.

Is the import missing within the framework or am I missing something else?

Thanks,

GA

**Comment by pragnagopa** [comment]
This is expected. Application needs to add WebKit framework.

**Comment by damienpontifex** [comment]
Cocoapods allows specifying "A list of system frameworks that the user’s target needs to link against." Not sure whether adding the WebKit as a requirement to the podspec would resolve this at least for those using cocoapods. i.e. adding to MicrosoftAzureMobile.podspec
```ruby
s.frameworks = 'WebKit'
```

**Comment by edmail** [comment]
That solved my problem, thank you galicu

**Comment by seletz** [comment]
What's the status here? Seems to me that the podfile wasn't updated?

**Comment by pragnagopa** [comment]
@shrishrirang - Can you please follow up on this

**Comment by dhei** [comment]
Thanks to @damienpontifex  and @seletz! Fixed in https://github.com/Azure/azure-mobile-apps-ios-client/commit/6523404f5fe7239ed6e23eeb53c58e4a1c2d9f62

**Comment by seletz** [comment]
Ok, this works now.  I think you could close this issue?
