### ISSUE TITLE
Utilize NSISO8601DateFormatter

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-mobile-apps-ios-client#77]
_For the backlog:_ With iOS 10, Apple has introduced the [NSISO8601DateFormatter](https://developer.apple.com/reference/foundation/nsiso8601dateformatter) which should be able to replace the `MSNaiveISODateFormatter` class in the project when iOS 10 is released later in the year.

**Comment by elamalani** [comment]
@damienpontifex Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us prioritize in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
