### ISSUE TITLE
Reuse https connection across different requests to server

### ISSUE THREAD

**Issue by shrishrirang** [Azure/azure-mobile-apps-ios-client#84]
- https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/src/MSClientConnection.m#L183 creates a new session for every request
- The same session should be reused across multiple network calls. (Need to check though that this will fix the issue of reusing the same connection for multiple requests)

**Comment by kabir-chandhoke** [comment]
Hi

Is there a work around or an ETA for this issue? Would really appreciate some help here. 

-Kabir

**Comment by shrishrirang** [comment]
As a workaround, it is possible to use the `MSClient:clientWithFilter:` method to define a filter which can be used to make network calls. The custom implementation can reuse https connections across different requests. I think reusing the `NSURLSession` used to make the connections should help, but I am yet to try that.
