### ISSUE TITLE
Compile error in Obj-C++ mode

### ISSUE THREAD

**Issue by Promit** [Azure/azure-mobile-apps-ios-client#85]
MSPush.h contains a function argument named "template". When compiled as Obj-C++ into a .mm file, this conflicts with the C++ keyword and causes a compile error.

**Comment by shrishrirang** [comment]
Depending on how your code is structured, you can consider separating the C++ and obj-C parts of your code into separate files, till this issue is fixed.

**Comment by Promit** [comment]
Changing the name of the parameter in the header (without changing the function signature, so that's the second "template" only and doesn't require a recompile) is sufficient to fix it, so it's not a blocking issue for me. Just an oversight.

**Comment by elamalani** [comment]
@Promit Since it's not a blocking issue for your application, I am closing this one but feel free to reach out if you have more questions. Thanks!
