### ISSUE TITLE
Custom HttpFilters are not invoked for login operations in iOS Mobile Apps SDK

### ISSUE THREAD

**Issue by chomique** [Azure/azure-mobile-apps-ios-client#86]
Our Mobile App backend API is published via Azure API Management. Because of that we need to ensure that each request has custom API-M header added to it for management, telemetry and tracking purposes. We have observed that custom headers are added to invokeAPI calls without any problem, but they are not added to the login requests despite the fact that we using custom http filter to add them.

Our code initializing the SDK client:
`service.client = [[MSClient clientWithApplicationURLString:kClientUrl] clientWithFilter:service];`

Our implementation of handleRequest method:

```
(void)handleRequest:(NSURLRequest *)request next:(MSFilterNextBlock)next response:(MSFilterResponseBlock)response{
    NSMutableURLRequest *newRequest = [request mutableCopy];
    [newRequest addValue:kOcpApimSubscriptionKeyValue forHTTPHeaderField:kOcpApimSubscriptionKeyName];

    next(newRequest, response);
}
```

Invocation of login method:
`[self.client loginWithProvider:kAdProviderIdentifier token:payload completion:^(MSUser * _Nullable user, NSError * _Nullable error)`

This seems to be a missing behavior, as we need some level of control over login requests.

**Comment by elamalani** [comment]
@chomique Thanks for using Azure Mobile Apps and your interest in adding this feature in the SDK. Please refer to the section on the ReadMe that highlights the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-ios-client#future-of-azure-mobile-apps). At this time, we are not adding any new features in the SDK but your interest will help us in the future.

Hope this helps. I'll close this issue but feel free to reach out if you have any other questions.
