### ISSUE TITLE
SBNotificationHub should or should not be included in this framework?

### ISSUE THREAD

**Issue by Shmaff** [Azure/azure-mobile-apps-ios-client#89]
Hi,

Is this new MicrosoftAzureMobile framework designed to only replace WindowsAzureMobileServices framework or is it also designed to replace the WindowsAzureMessaging framework? I heard there was an effort to combine these frameworks into one but obviously SBNotificationHub is not here. Am I mistaken in believing these will/should be combined into this new one?

**Comment by adrianhall** [comment]
This replaces the WindowsAzureMobileServices.  It isn't meant to replace the WindowsAzureMessaging framework.
