### ISSUE TITLE
Google removing OAuth support for UIWebView 

### ISSUE THREAD

**Issue by edorphy** [Azure/azure-mobile-apps-ios-client#90]
Google announced today that they will be removing OAuth login support using UIWebView. This means no one would be able to use Google as an OAuth provider.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

Same applies for Android WebView

"In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”, such as the WebView UI element on Android and UIWebView/WKWebView on iOS, and equivalents on Windows and OS X."

**Comment by danderson00** [comment]
There will certainly be some changes required here. It doesn't mean we have to stop using the google OAuth provider, it simply means we need to carry out the login UI flow in a device browser, rather than using an embedded UIWebView.

Will keep you posted on this.

**Comment by edorphy** [comment]
Everyone using app services can use deep linking. If the app is properly configured, SFSafariViewControllwr can redirect to ones app delegate. 

What is the API/Endpoint contract that the auth callback invokes? It would be an acceptable solution to call that API when the app delegate gets its continue user activity. Another idea would be to hide the redirect behind a domain that is not under universal links. Then when the URL does #done instead redirect to a URL the developer provides. 

I would really NOT want to just use Google's GOogle ID Signin library.

**Comment by danderson00** [comment]
We're spending time now working out the impact on us and our strategy. It would appear that all of our client SDKs are affected. We'll keep you posted on the plans very soon!

**Comment by mattchenderson** [comment]
Related: https://github.com/Azure/azure-mobile-apps-net-server/issues/156

**Comment by shrishrirang** [comment]
We are working on this. The plan is to use `SFSafariViewController` when available and fallback to `WKWebView` if required. When using `SFSafariViewController` the authentication token will be sent to a URI with a custom scheme. The app will have to register for the custom scheme and when notified will have to call an API in the SDK to continue the authentication flow. The SDK will respond by connecting to the Azure backend and acquire the access token using the authentication token.

The implementation will adhere to https://tools.ietf.org/html/rfc7636 - specifically, it will use `code_challenge` to mitigate the threat of a malicious app hijacking the flow by registering for the same custom scheme.

**Comment by edorphy** [comment]
What about using the apple-app-site-association instead? This was the direction I was hoping this would go in. The fact that you have to host this json file on your site (Azure App Service) and then the bundle identifier has to match the app, there is no concern for MITM.

Instead of white listing your entire domain under the apple-app-site-association we could do all but a certain path, say /.auth/, reserve that for Azure to used in the Google Auth callback. Once token request complete and in the token store, Azure could redirect to another part of our domain listed in the Association file.

The whole point of the SFSafariViewController and OAuth was to get away from custom schemes. Apple has even said that its the way of the past, and could go away. They favor universal links. Even Google supports a similar link opening mechanism as of Android 6.0+.

**Comment by shrishrirang** [comment]
@edorphy Universal links are clearly the better choice for most scenarios.

For OAuth initiated from a native app, the benefits are limited though. We know the native app exists, there is no conditional launch of native app involved, so no dealing with the usual mess of launching external custom schemes. Plus, the configuration needed when using custom schemes is way simpler than that involved while using universal links. The authentication _server flow_ is intended to be a quick way to add authentication to the app. For a more iOSish (and Android-ish) experience, we [encourage](https://azure.microsoft.com/en-us/documentation/articles/app-service-authentication-overview/) using native provider specific library coupled with the SDK's _client flow_.

Is there any official Apple communication that custom schemes are deprecated? WWDC 2015 introduced universal links and safari view controller both at the same time and Apple officially recommended using custom schemes for OAuth in native apps.

Android versions with support for universal links (App links) have a very small market share ([~19%](https://developer.android.com/about/dashboards/index.html)) so we need to go the custom scheme way for Android. Using custom schemes for authentication on iOS keeps the SDK behavior consistent across Android and iOS.

**Comment by dhei** [comment]
We released SDK [v3.3.0](https://github.com/Azure/azure-mobile-apps-ios-client/releases/tag/3.3.0) today with support for SafariViewController Login.

**Comment by valterh4ck3r** [comment]
How to use provider google auth, in ionic apps right now ?

**Comment by randeep80** [comment]
May I know what option is given for Android projects, Similar controller using Chrome?

**Comment by danderson00** [comment]
Hi @randeep80 we recently released the Mobile Apps Android SDK with support for authentication using custom tabs. See the change log at https://github.com/Azure/azure-mobile-apps-android-client/blob/master/CHANGELOG.md.

**Comment by randeep80** [comment]
Hi @danderson00 , is this SDK applicable for Xamarin as well?

**Comment by danderson00** [comment]
Xamarin support is being implemented by the Xamarin team. There is an issue tracking this [here](https://github.com/xamarin/Xamarin.Auth/issues/137).

**Comment by dhei** [comment]
Hi @randeep80, for Mobile Apps Android SDK support of Chrome customtabs in login, you may follow the documentation [here](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-users#add-authentication-to-the-app). We updated the documentation today for this change.

**Comment by idoMintzDev** [comment]
what about cordova/Andoird  any solution?
