### ISSUE TITLE
processPullOperation throws EXC_BAD_ACCESS on upsertItems function

### ISSUE THREAD

**Issue by jaimeeee** [Azure/azure-mobile-apps-ios-client#94]
I'm calling `table!.pullWithQuery(self.table?.query(), queryId: "AllRecords")` (copy and paste from the example) and it throws an error here:

```Obj-C
// upsert each item into table that isn't pending to go to the server
[self.syncContext.dataSource upsertItems:itemsToUpsert table:self.query.table.name orError:&localDataSourceError];
if ([self callCompletionIfError:localDataSourceError]) {
    return;
}
```

It gives an EXC_BAD_ACCESS:

<img width="852" alt="screen shot 2016-08-31 at 19 09 56" src="https://cloud.githubusercontent.com/assets/258357/18150767/0722c320-6faf-11e6-8e45-003f66a671d0.png">

Any idea?

**Comment by antitheos** [comment]
@jaimeeee was there ever a solution to this problem? I am having the a similar problem
