### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by dmgerdes** [Azure/azure-mobile-apps-ios-client#99]
Is there any development being made for supporting Swift 3.0?

**Comment by adrianhall** [comment]
Swift 3 is supported with XCode 8.1 - you just have to convert your project.

**Comment by dmgerdes** [comment]
I was able to get my project to work on xcode 8.1 but not with xcode 8.0.  I've since closed my ticket with microsoft.

**Comment by adrianhall** [comment]
Understood - XCode 8.0 had a broken project converter.
